oat-sa/lib-tao-qti

composer.json

The idea is to restrict the use of QTI-SDK 0.9.x in lib-tao-qti. In the (very next) future, we would like to develop a QTI-SDK 0.10.x for TAO, to be integrated gradually across vendor specific projects.
Moreover, this enables us to begin the tagging process on lib-tao-qti.

Restrict lib-tao-qti to QTI-SDK 0.9.x.

---

composer.json

@antoinerobin If released as 2.1.1, will make its way automatically to local repos !

Reference exact qtisdk legacy version to avoid issues.

---

composer.json

Upgraded QTI-SDK to legacy version 0.19.0:
This version adds support for:
- QTI 2.2 `externalScored` attribute in outcome declaration.
- PHP 7.4:
- Code in the form of `a ? b : c ? d : e` without proper parentheses is deprecated and will break in the next version of PHP
- Accessing `null` as an array does not return `null` any more. `?? null` has been added in Json marshaller.
- Travis execution of all tests (PHP 7.0 to 7.4).
Support for PHP < 7.0 is dropped.

Feature/ms 59/external scoring

---

composer.json

QTI-SDK 0.19.0 dropped support for PHP < 7.0.

Dropped support for PHP < 7.0.

---

composer.json

- UDI-26 chore(dependencies): allow minor upgrades of `qtism/qtism` in end applications

UDI-26: Lift a strict restriction on dependencies versions

---

composer.json

This Pull Request aims at providing Integration Testing of the future `0.21.0` release of QTI-SDK. As soon as the Integration Testing is done by QA, the following line in the `composer.json` file.
```json
...
"qtism/qtism": "dev-feature/tca-666/aria-attributes-legacy",
...
```
must be replaced with
```json
...
"qtism/qtism": "0.21.0",
...
```
**Please pay attention that the Integration Testing of QTI-SDK `0.20.0` is still on hold. We need to push on this first,** and then get another round for `0.21.0`. Please see [QI-316](https://oat-sa.atlassian.net/browse/QI-316).
Finally, merging this PR must result in the release `5.2.0` of `lib-tao-qti`.
**This PR is a companion PR of:**
* https://github.com/oat-sa/qti-sdk/pull/198
* https://github.com/oat-sa/extension-tao-itemqti/pull/1483

Feature TCA-666 Aria Attributes Support

---

composer.json

*Integration of QTI-SDK Legacy 0.22.0*
**Added**
- Compilation to QTI 2.2
- <a> tag in interaction prompt (QTI 2.2 feature)
- Parsing of large XML text nodes

QTI-SDK 0.22.0

---

composer.json

This PR includes QTI-SDK 0.22.1 for ellipse collision detection fix.
See https://github.com/oat-sa/qti-sdk/pull/217 for more details.

Upgraded QTI-SDK legacy to 0.22.1.

---

composer.json

Changed version constraint from `~0.0.0` (equivalent to `>=0.0.0 & <0.1.0`) to `^0.0.0` (equivalent to `>=0.0.0 & <1.0.0`) to get the latest version below breaking change

Changed lib-beeme version constraint to get latest version below breaking change.

---

composer.json

This PR includes two upgrades of QTI-SDK:
- 0.22.2: Fixed implementation of expectedLength and expectedLines for ExtendedTextInteraction and TextEntryInteraction
- 0.22.3: Added LIBXML_BIGLINES flag to allow XML parser to deal with line numbers greater then 65535

Upgraded QTI-SDK legacy to 0.22.3.

---

composer.json

This PR includes one upgrade of QTI-SDK:
- Support for storage of a hash of an uploaded file instead of the content of the file itself, to avoid huge payloads to be stored in the test session. Please read https://github.com/oat-sa/qti-sdk/pull/227 description for more details and usage example.

Upgraded QTI-SDK legacy to 0.22.4.

---

composer.json

In PHP 8.*, `match` is a reserved word, the Match operator class has been renamed `MatchOperator` but former Tao compiled tests still contain generated PHP code with references to the `Match` class.
This PR makes sure these compiled tests still run in PHP 7.*.
However, when run on PHP 8.0, the older compiled tests containing usages of the `Match` class will have to be updated either by re-publishing or by running a script to update the generated PHP code.

Fixed PHP 7 Match operator support.

---

composer.json

Fixed minChoices in HottextInteraction and PositionObjectInteraction to be valid when greater than maxChoices if and only if the latter is 0.

Upgraded QTI-SDK to 0.24.4

---

composer.json

Upgrade `qti-sdk` to `0.24.12`, introducing precondition rules are checked on all test parts, sections and items, not only on first item in section.

Merge for release 7.2.1

---

composer.json

Include QTI-SDK legacy 0.24.12 for TR-1648

fix: include QTI-SDK legacy 0.24.12 for TR-1648

---

composer.json

- Support of 'list' type in a record, fix incorrect response in case of 'list' types

chore(version): require qtism/qtism v0.25.0

---

composer.json

- fix: unify acceptable latency influence on `mmove` and `jump` behavior

fix: require `qtism/qtism` `v0.25.1`

---

composer.json

Required QTI SDK 0.26 version including feature: https://github.com/oat-sa/qti-sdk/pull/313

feat: require qti-sdk 0.26

---

composer.json

https://oat-sa.atlassian.net/browse/AUT-2337
Import/export shared stimulus and keep the "lang" and "dir" attributes is not working.
Example where the problem happens: https://github.com/oat-sa/extension-tao-mediamanager/blob/master/model/sharedStimulus/encoder/SharedStimulusMediaEncoder.php#L51 When we call XmlDocument::load() it does not keep the attributes we need. 
- Add possibilities for custom attributes in the BodyElement
- https://github.com/oat-sa/qti-sdk/pull/318
- https://github.com/oat-sa/extension-tao-itemqti/pull/2162

chore: update qtism version

---

composer.json

Related to: https://oat-sa.atlassian.net/browse/TR-4212
Update QTI-SDK to version `0.28.1`.
Removes the double encoding of attributes (see https://github.com/oat-sa/qti-sdk/pull/325)

Fix/TR-4212/Decode HTML entities in attributes

---

composer.json

Update QTI-SDK to version `0.28.1`.
Removes the double encoding of attributes (see https://github.com/oat-sa/qti-sdk/pull/325)

Release 7.7.1
