oat-sa/lib-tao-qti

- composer.json
- helpers/class.AbstractStateOutput.php
- helpers/class.LegacyStateOutput.php
- helpers/class.LegacyVariableFiller.php
- helpers/class.PciJsonMarshaller.php
- helpers/class.ResultTransmitter.php
- helpers/class.Utils.php
- model/operators/math/graph/CountPointsThatSatisfyEquation.php
- model/operators/text/StringToNumber.php
- test/LegacyStateOutputTest.php
- test/PciJsonMarshallerTest.php
- test/PciStateOutputTest.php
- test/PciVariableFillerTest.php
- test/operators/CountPointsThatSatisfyEquationTest.php
- test/operators/StringToNumberTest.php
Related to:
https://github.com/oat-sa/qti-sdk/pull/32
https://github.com/oat-sa/lib-tao-qti/pull/9
https://github.com/oat-sa/generis/pull/185
https://github.com/oat-sa/extension-tao-testqti/pull/456
> PHP7 Support

- model/operators/CsvToContainer.php
- model/operators/CsvToMultiple.php
- model/operators/CsvToOrdered.php
- test/operators/CsvToMultipleTest.php
- test/operators/CsvToOrderedTest.php
Could you please just check that the code is not ugly and that unit tests are OK? Thanks.
> TAO-2753 CsvToMultiple and CsvToOrdered operators.

- composer.json
- model/operators/math/graph/CountPointsThatSatisfyEquation.php
requires https://github.com/oat-sa/lib-beeme/pull/8
> use precision precision from required lib-beeme v0.2

- helpers/class.ResultTransmitter.php
WIP
depends on https://github.com/oat-sa/extension-tao-outcome/pull/101
> Get rid of statefull service

- composer.json
> Merge develop into master for release 5.0.0

- composer.json
This PR keeps allowing only MINOR changes for QTI-SDK, not MAJOR.
> Allow only minor version upgrades for QTI-SDK.

- composer.json
Upgraded qti-sdk legacy to 0.22.0.
Tested thoroughly with Tao Community, by creating test before the upgrade, doing the upgrade and taking the test with the new version.
> Feature/ms 152/compile qti 22

- composer.json
This PR includes QTI-SDK 0.22.1 for ellipse collision detection fix.
See oat-sa/qti-sdk#217 for more details.
> Merge for release 5.3.1

- composer.json
> Merge for release 5.4.1

- composer.json
This PR updates and fixes lib-beeme version to 0.2.0.
> Upgraded lib-beeme to 0.2.0.

- composer.json
Compatibility pack for Match operator in PHP 7
> Merge for release 7.0.1

- composer.json
Upgrading QTI-SDK for https://github.com/oat-sa/qti-sdk/pull/253
> Changed regex for QTI class producing too many steps.

- composer.json
> Merge for release 7.0.2

- composer.json
Upgraded QTI-SDK to version 0.24.3.
> Added XSD for QTI 2.2.3 ans 2.2.4.

- composer.json
Upgraded QTI-SDK to version 0.24.3.
> Merge for release 7.1.0

- composer.json
> Merge for release 7.1.1

- composer.json
> Merge for release 5.6.1.

- composer.json
> Merge for release 7.1.2

- composer.json
> Merge for release 7.1.3

- composer.json
> Merge for release 7.1.4

- composer.json
> Merge for release 7.1.5

- composer.json
> Merge for release 7.1.7

- composer.json
Upgrade `qti-sdk` to `0.24.11`, introducing fast-forward to the last item and close the test session.
> Merge for release 7.2.0

- composer.json
This Pull Request aims at integrating the latest fixes (preCondition issues) inclued by release of QTI-SDK Legacy `0.24.12`
> fix: add QTI-SDK fix from 0.24.12

- composer.json
Include QTI-SDK legacy 0.24.12
> Hotfix/tr 1848/preconditions assessmentsections

- composer.json
include qti-sdk legacy 0.24.12
> fix: include qti-sdk legacy 0.24.12

- composer.json
- fix: XML-encode a value before inserting it into DOM
> chore(version): require `qtism/qtism` `v0.24.13`

- composer.json
Upgrade `qti-sdk` to `0.24.13`, introducing XML value encoding
> Merge for release 7.2.2

- composer.json
https://oat-sa.atlassian.net/browse/TR-3373
What is it about?
ExtendedText or InlineText with pattern: submit fails if validateResponses is set
1. already tested
No dependencies
TODO
> fix: update legacy release for TR-3373

- composer.json
Update QTI SDK version by 0.26.1
> Update QTI SDK version by  0.26.1

- composer.json
> Develop -> master

- composer.json
Feat: add qtism 0.27.0
Merge https://github.com/oat-sa/lib-tao-qti/pull/121
> feat: add qtism 0.27.0

- composer.json
> chore: update qti-sdk with support ruby tag

- composer.json
apply latest changes [TR-4839](https://oat-sa.atlassian.net/browse/TR-4839)
> chore: udpate ruby tag to build inline

- composer.json
the goal of this PR to simplify restriction of QTI-SDK version but minimal necessary version
> feat: apply less restricted version of qti-sdk
